### PR TITLE
fix #204: Ensure --baseline in combination with a --dryrun doesn't create the grate schema objects

### LINKED ISSUE #204: `--dryrun` does nothing in combination with `--baseline`
**Describe the bug**
Dry running a baseline does not work.

**To Reproduce**
Run `grate -cs $CS --baseline --dryrun`. Observe that `grate` has applied the baseline to the database, created a `grate` schema, three tables and marked the migrations as run.

**Expected behavior**
`grate` prints what would happen, but does not write anything to the database.

### PR DESCRIPTION
**Pull request by wokket**

### CODE REVIEW

File: grate/Migration/AnsiSqlDatabase.cs [hunk 1]
```diff
@@ -288,9 +288,17 @@ protected virtual string ExistsSql(string tableSchema, string fullTableName)
...
-        var sql = CurrentVersionSql;
-        var res = await ExecuteScalarAsync<string>(Connection, sql);
-        return res ?? "0.0.0.0";
+        try
+        {
+            var sql = CurrentVersionSql;
+            var res = await ExecuteScalarAsync<string>(Connection, sql);
+            return res ?? "0.0.0.0";
+        }
+        catch (Exception ex)
```
Comment (erikbra) [inline grate/Migration/AnsiSqlDatabase.cs:297]: I know this is merged, so this is more of a general comment. I'm very sceptical to catching `Exception` in general, as this could be everything from `OutOfMemoryException` to `FileNotFoundException`, so I think we should narrow this catch a lot down, if possible. And, if it's always a generic `DbException` or sim, we could try to look a bit at the details to make sure it's actually. the exxpected error we are getting, so that we don't swallow any other exception by mistake :)

File: grate/Migration/AnsiSqlDatabase.cs [hunk 2]
```diff
@@ -354,13 +362,24 @@ private class ScriptsRunCacheItem
...
 FROM {ScriptsRunTable} sr
 WHERE id = (SELECT MAX(id) FROM {ScriptsRunTable} sr2 WHERE sr2.script_name = sr.script_name)
 ";
-        var results = await Connection.QueryAsync<ScriptsRunCacheItem>(sql);
-        return results.ToDictionary(item => item.script_name, item => item.text_hash);
+            var results = await Connection.QueryAsync<ScriptsRunCacheItem>(sql);
+            return results.ToDictionary(item => item.script_name, item => item.text_hash);
+
+        }
+        catch (Exception ex) when (Config?.DryRun ?? throw new InvalidOperationException("No configuration available."))
```
Comment (erikbra) [inline grate/Migration/AnsiSqlDatabase.cs:378]: I think we should maybe isolate this exception handling that is done both above ( my previous comment), and below in `GetScriptsRunCache` , into a more general concept (a proxy/wrapper of some sorts), to avoid performing almost the same exception handing many places in a situation that is in essence an expected situation (although very rare) :)

**Comment by erikbra** [comment]
Thanks a lot, @wokket ! Great work :)
I see a future abstraction of the `--dryrun` handling in some form - an own DbMigrator implementation for dryrun? A wrapper around the actual execution of the scripts? A Dryrun DbConnection? At least, something. But, we can look into that later :) We can always refactor later, when we have good tests!

File: grate/Migration/AnsiSqlDatabase.cs (hunk 1 above)
Comment (wokket) [reply grate/Migration/AnsiSqlDatabase.cs:297]: Completely agree.  I can't even remember which exception type I was seeing when I wrote this!

File: grate/Migration/AnsiSqlDatabase.cs (hunk 2 above)
Comment (wokket) [reply grate/Migration/AnsiSqlDatabase.cs:378]: I think I'd rather see  a better thought out impl of `dryrun` than I wrote originally rather than an attempt to arbitrarily  centralise error handling which is always going to be situation specific.

Comment (erikbra) [reply grate/Migration/AnsiSqlDatabase.cs:378]: I agree. We need to re-think it a bit. We need to look a bit more into it. I don't think a _single_ "DryRunConnection" would solve it, as there does need to be database specific ones, but we might wrap the DbConnection implementations or similar, to make the "if dryrun" logic _one_ place. 

Let's ponder a bit, and get back to it
